name: CI

on:
  push:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: xd1
        run: |
          echo "TEST_ENV=PRod" >> $GITHUB_ENV
      - name: hello
        run: |
          echo 'console.log("abc".toUpperCase())'
          echo "Hello World"