name: CI

on:
  push:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: xd1
        run: |
          echo "TEST_ENV=prod" >> $GITHUB_ENV
      - name: hello
        run: |
          echo "${{ env.TEST_ENV }}"