name: CI

on:
  push:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Run a one-line script
        run: |
          mkdir -p secrets/decrypted/
          echo '${{ secrets.SAMPLE }}' >> secrets/decrypted/secrets.txt
          echo "File Created"

      - name: Run a multi-line script
        run: |
          echo Add other actions to build,
          echo test, and deploy your project.
          echo ${{ secrets.SAMPLE }}
          cat secrets/decrypted/secrets.txt
          cat $(readlink -f secrets/decrypted/secrets.txt)

      - name: Print Env variable
        run: |
          echo "All"